services:
    api: &api
        image: juntos-somos-mais-api:debuggable
        command: ${COMPOSE_DEVELOPMENT_COMMAND:-}
        build:
            target: debuggable
        environment:
            PYDEVD_DISABLE_FILE_VALIDATION: "true"
        ports:
            - ${APP_HOST_PORT}:${APP_HOST_PORT}
            - ${APP_DEBUG_PORT}:${APP_DEBUG_PORT}
        volumes:
            - ./api:/app/api
            - ./tests:/app/tests

    runner:
        <<: *api
        command: /bin/ash
