services:
    api: &api
        image: juntos-somos-mais-api:development
        command: ${COMPOSE_DEVELOPMENT_COMMAND:-}
        build:
            target: development
        environment:
            PYDEVD_DISABLE_FILE_VALIDATION: true
        ports:
            - ${APP_HOST_PORT:-8000}:${APP_HOST_PORT:-8000}
            - 5678:5678
        volumes:
            - ./api:/app/api
            - ./tests:/app/tests

    runner:
        <<: *api
        command: /bin/ash
