services:
    api: &api
        image: juntos-somos-mais-api:latest
        container_name: api
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - ${APP_HOST_PORT}:${APP_HOST_PORT}

    runner:
        <<: *api
        command: /bin/ash

    prometheus:
        image: prom/prometheus:v2.52.0
        container_name: prometheus
        volumes:
            - ./.monitoring/prometheus/:/etc/prometheus/
        ports:
            - 3000:9090

    grafana:
        image: grafana/grafana:11.0.0
        container_name: grafana
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
        volumes:
            - ./.monitoring/grafana/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            - ./.monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
        depends_on:
            - prometheus
        ports:
            - 3001:3000
