groups:
  - name: JuntosSomosMaisApi Alerts
    rules:
      - alert: ApiHealth
        expr: up{job="JuntosSomosMaisApi"} < 1
        for: 5s
        labels:
            severity: critical
        annotations:
            summary: Api HealthCheck
