kind: Secret
apiVersion: v1
metadata:
    name: juntos-somos-mais-api-secrets
    namespace: production-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:Q5Ejzw==,iv:JWaa2LatLiyHxAgHD3Mdf0xaXu+vOamE89UShLBQA2w=,tag:loRdIhO/YGQ0edPfklHeng==,type:bool]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:G4/85Oc5xyUSZw==,iv:eQ0OZRHCrBLs8eLZDZ13z+rZsLoT4Jlm0PnP36Xdr6o=,tag:k1EqbwbQMU9AFjTgASqaMA==,type:str]
    APP_HOST: ENC[AES256_GCM,data:Et5j4QvwmQ==,iv:oUlGQj3nkK471ingQPVBMulegjmj69wAr/Pb61DPCjc=,tag:GrI+9b86gdCSpIf0CM8iQg==,type:str]
    APP_HOST_PORT: ENC[AES256_GCM,data:BgQ=,iv:rbid3MKHM7czKnsZstEmuDNhKU88Ph8Uc2Zl3+j20v8=,tag:+A2F+i3dQGsPE9BkA4dJfQ==,type:str]
    APP_PREFIX: ""
    JSM_DATA_URL: ENC[AES256_GCM,data:YDXh36yDWVl7vkubStBKy0rFlZqTlNtX+rmfZxQ+ona84mrXeQ8cVhVlV3vPZKV/85WWuoowQE1ZfdKHAw==,iv:a1fR+DDdPtgYR7FoP89lyVKidYJ8SDiXZuzKHHQeRFQ=,tag:QNSQOAFiigFJjeLvyjMFew==,type:str]
    IBGE_DATA_URL: ENC[AES256_GCM,data:WMJ2G0xNLq0lK+OxW+5Yc3Qozj96v8QK7sj4DYkpOvUIxO74vE4rxQ89Wfcm60qE+vDy,iv:zX0vJ/yHNkXjqJuY6VgJeraL3xJq3KCEHsS2zFnuvUg=,tag:FYHhB0BmU5py9R/se3qbYA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:BuLALc/+FIMlD19DkVTSx6V0Hjc4FW23NajjlKjLLE0QkZYy,iv:EMsI0UZN8ff4jI4MQDWCB9STIJcToE4SWCq5xmAZisA=,tag:DUBmG20KUfNihTlJAGmJVg==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:bBdM4QM=,iv:Iti3UA4wQGE0GAGzsOtf2Un7AKb2rCZ/sPBoeYGcnak=,tag:AfPZMxFb4pMh7VuuW+tl4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RWNVaHFQcjRkdS9sM3pO
            NjJuSzc0OGxMbk5FUjlDekd0TjdGd1YzUXlRClFlZUtNU0tWZFlJdHpjSkdGWjM3
            QzNRYzBJWWVCblU3NkdxYU1GNFpiTncKLS0tIERFZ1pMS0lzdVBRNHZvUXZhaktI
            R0w2NFNqWHUwTVkxV081allMNUQ1a0kKR+VLFm5AMvWwd3eBoGYOVG4O2Zgmld1f
            /qG+YyGKWU7FqdyeOkXFvCR8rZcbFanBraQPcW9KjV6J+Qcxgp1XiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T20:43:02Z"
    mac: ENC[AES256_GCM,data:zDvtbxkXvDgW9iuwpkpIuG1W2OTlfmWiIa8zF3BihicKkfVwe8c7VAKmuVE5WjanX/jkWwpbJQvrMlfoR5HDEHPuPv9/Tf5eioANuyM6gCfWoNFpQHp5O7fmzvKnwNY+MifFbvP9AsLUhTANVuOfrryyXAB8eP+Km9sV5M3wc/k=,iv:0KKF16gBYWiglNDn2TgcvE1Z0KxpUlVwZ5v+tmPL2Po=,tag:rGhwfs2vJPz8LLCpYlK7ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
