kind: Secret
apiVersion: v1
metadata:
    name: juntos-somos-mais-api-secrets
    namespace: staging-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:KlYd4g==,iv:VX6GRDjpBcrUJmVaaakjouGr9dNtmEDbmQDILCP88XY=,tag:jARTX1utkh5R57C68n9RqQ==,type:bool]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:7gOHwoQIyA==,iv:LI5mU0/YovhuXMdcMmNNpVJhk4Q9hN9DJF+eBKR7ZUA=,tag:5dKJLifPGiLZNd8N9yFq/g==,type:str]
    APP_HOST: ENC[AES256_GCM,data:18Bhgq0S+A==,iv:TulkF8RCchtM97qytKEvVIAg2u7OyRduqnIz6LMQLiI=,tag:Y8IStJOpvZNeG4YFUb3+hw==,type:str]
    APP_HOST_PORT: ENC[AES256_GCM,data:LoI=,iv:J9RzbIKHiMOTty3FznN8rbvVI8r3VLavItvV4wjXY0U=,tag:KLusrq5yXzQ6TfcuaO4VlQ==,type:str]
    APP_PREFIX: ""
    JSM_DATA_URL: ENC[AES256_GCM,data:wfsQtLxLL8AdYLYtIqab9Q/jzuHfNMq7YNYK8nRQVcKF+sxaRYx3Sbzn4xJqrD3QLovcHrJ97jB1PZm6eQ==,iv:9tsyadDnpxYtveLZpLTPcAfpKB1SbcBTs4+zEzCAKrM=,tag:xxpp7r9Tq33VboIxLghWfA==,type:str]
    IBGE_DATA_URL: ENC[AES256_GCM,data:2LREfLA6b92luiKgjDaP5rKDvMEYl7SlpvJtM+3wyRnZzTnJAWbNi7XcMKuEeTPOMrUQ,iv:GK3HCYYo7u6yFKfF8hk3xh9yefbZIRMaVExG/+0w3uo=,tag:4+dmcZH7r3m4GEdMvNX3/Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:0Y6E3ct3HBsIM0OTa9S1ZXyi1Zx7LGGXFnQsMy2zru/S4XFO,iv:hXdIu4/Ig6T2lRWnVWvcjpeKEUWCuNx5GWDzNB3Skuk=,tag:/nUp14/NuCXOn//NxWIXUw==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:nxxXvCc=,iv:WInqVRRGW8z8jt/fpjE28/rP2zoIBriReEXVU2f4GjU=,tag:9uudfPLeICnGW+HLcU4biw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T0V6R21kalZtRUsxTVht
            RExGR3Q1L2loWE9semVTSnQ1QXJpcXpIRW5NCnZjZ1BiSXo3MVFWRlRpejA2MElH
            ZTdiNHgzWEdLeFNUN0Y2UTZ4QXdWU3cKLS0tIDhJQUQvMGIrdXhJVFdiZlYzQTlB
            UUlKZ0hleGsvUHpuN3VCVDRrS2JkNzgKse8gBkePATiDD7pX9gOwdvbNIdMJCk2N
            j+WyYxyvMLGFbtJuoOq92bvbycXkRfBtTWCpQmr4O1omLb6bLLxLsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T20:43:06Z"
    mac: ENC[AES256_GCM,data:0/VY51qgH/fXYXGNJWufhFvhAvy7Y008vt9XcVk67UgRutrTj/cZHrKxfGLgbljGm0vpGfNCUtbf04Fq7Pq+CTrx1wDQ2+JJK42vRugeJ1zV9HIUkwJKXm3sNSLafuOjREZj2is17Zh9fG4iYMRU5slx2Qww7XHQrHvCFXBwGgE=,iv:GySK/jFV2TBw2grTJae+rNYKfyOCrjXEtcLkZAo0Btc=,tag:faPGPy2wkTllSr0/0p6f/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
