kind: Secret
apiVersion: v1
metadata:
    name: juntos-somos-mais-api-secrets
    namespace: staging-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:Hma/JQ==,iv:0hpOBawY5Za3NgxfO7QKgAUwQZ7Y/VVfHtTbhnP4nj8=,tag:IsVM+kqBbyOnphQ3lC6veQ==,type:bool]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:lYP+c4FUYA==,iv:nZusFjCUHBHCWv1f92UnsAPXeSXcYTUhyV0Q/FzDync=,tag:a4ymKmF8mrHipUJtZF/wtA==,type:str]
    APP_HOST: ENC[AES256_GCM,data:BSkwcmLHDw==,iv:5Un18V39IgFH6ZCwmpKXj6VtR0Ne863yGnSQex/4arg=,tag:1qkFEVkCFRDYokxxD066hg==,type:str]
    APP_HOST_PORT: ENC[AES256_GCM,data:wLA=,iv:jZS3ccy3blSKqZtl5whh8Rb2Hgp9tu6OI8KEzGg+j1c=,tag:iWLh6FuTcZ6dcRVwXxxJrg==,type:int]
    APP_PREFIX: ""
    JSM_DATA_URL: ENC[AES256_GCM,data:8mEoYxLwUCxeJZ44yFSgLzdLXZBsiaWy5OfSAautX7YShnVJJNLpqqIG2JFd+IsGKrXgRO7EFFcHeRVQRg==,iv:x0atEjBrEcjgdMQVTQCeKaBEeTWz9Xj0DtgQtlX50ZU=,tag:yFF8Vdr9UwgR+Bl00w063Q==,type:str]
    IBGE_DATA_URL: ENC[AES256_GCM,data:MlchZ3XKn7rGwNjCTeKs5zKy52CHuGWrqF+KILhYy5xJ0AwjnsttVJhFE181bwXUxxF6,iv:xvcwF0peE+2kHxxf03dd1ar3q1Xb9yW04wii5uMZs0E=,tag:SvMIVBEBytygajsOCa4/HA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:JdvWX+gmymlYv9w8PjUKaZHaFpJbXhsFHIk4oospHmf9h5lV,iv:Q/f7gXd3HMMRDVyZBbC8ADakBj+KyyiMgJRkTWK9xFs=,tag:S1iajc20Ubn33754NeisDg==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:v4r4YPI=,iv:FsUaoKxQK2quGFkcWv6kHaJTe6obXC75+BxNUjEnYxI=,tag:YWtW0MU8rDr5MBpSC3Sjzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTNKcFNzQnBpWGVHVjNw
            anNXNitMZWlxWFVXT0RUQlJMS25TSlNnRlFRClJ1ekNWQjc1WStjY3JpR1hqdW50
            N3hybWpLRHBjQlRZeWIvWGFSWWFNeTQKLS0tIDNqb1lpcTlXd2ppWSsrK1hOR0VU
            bUZudHh6azF3Y3oxRTNub1E2NjFoS1kKY5oIopefT3ut1PqjU1YJ540SSTxFpumJ
            JBFbY3CqZYWFas2AO41+0nnWAlqr1JXlyBr0GxtF5jJ7lXGYUiTTQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T20:24:52Z"
    mac: ENC[AES256_GCM,data:DXo10LubaIuXanw/3QYagUzE/EmbVryaUU17pGWq/D84sq8lhn1yzfs2sgNCFUZ8uTC/TsInyJLinL+OSQhkskNEswEL+n9gfhtF0VHqgk4DxkhFxrZTQ80ULTUZiwb2H/wkptM97ivGbaaPLPz0tqVWHokTewtwflVzXNiPcN4=,iv:/mgsbmVCyBxbwUJHFdL6zxpb8iJRnqHwc9GEQjbjBUI=,tag:5DLCrYBxdz0DEvwgjnn7JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
