kind: Service
apiVersion: v1
metadata:
    name: juntos-somos-mais-api-service
    namespace: production-apps
spec:
    selector:
        app: juntos-somos-mais-api
    type: LoadBalancer
    ports:
      - name: http
        port: 8082
        protocol: TCP
        targetPort: 8000
