name: JuntosSomosMaisApi - on-push-tags

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]"
            - "[0-9]+.[0-9]+.[0-9]-staging"

jobs:
    reusable-workflows:
        uses: Artbsides/ArgoCD.Deployment/.github/workflows/on-workflow-call.yml@main
        secrets: inherit
